# Generated by Django 4.2.5 on 2023-09-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import realtybooking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(validators=[realtybooking.models.validate_start_date])),
                ('end_date', models.DateTimeField(validators=[realtybooking.models.validate_end_date])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtybooking.room')),
            ],
        ),
    ]
