# Generated by Django 4.2.5 on 2023-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtybooking', '0004_alter_room_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='realtybooki_room_id_ab435d_idx',
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'start_date'], name='realtybooki_room_id_4c9972_idx'),
        ),
    ]
